/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAuthAdminRouteImport } from './routes/_authenticated/_authAdmin'
import { Route as AuthenticatedCollectionIdRouteImport } from './routes/_authenticated/collection/$id'
import { Route as AuthenticatedCollectionIdDocumentsRouteImport } from './routes/_authenticated/collection/$id/documents'
import { Route as AuthenticatedCollectionIdChatRouteImport } from './routes/_authenticated/collection/$id/chat'
import { Route as AuthenticatedAuthAdminAdminUsersIndexRouteImport } from './routes/_authenticated/_authAdmin/admin/users/index'
import { Route as AuthenticatedAuthAdminAdminUsersIdRouteImport } from './routes/_authenticated/_authAdmin/admin/users/$id'
import { Route as AuthenticatedAuthAdminAdminCollectionNewRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/new'
import { Route as AuthenticatedAuthAdminAdminCollectionIdRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$id'
import { Route as AuthenticatedAuthAdminAdminCollectionIdUsersRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$id/users'
import { Route as AuthenticatedAuthAdminAdminCollectionIdUpdateRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$id/update'
import { Route as AuthenticatedAuthAdminAdminCollectionIdReindexRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$id/reindex'
import { Route as AuthenticatedAuthAdminAdminCollectionIdInsertRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$id/insert'
import { Route as AuthenticatedAuthAdminAdminCollectionIdDocumentsRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$id/documents'
import { Route as AuthenticatedAuthAdminAdminCollectionIdDeleteRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$id/delete'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthAdminRoute = AuthenticatedAuthAdminRouteImport.update({
  id: '/_authAdmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionIdRoute =
  AuthenticatedCollectionIdRouteImport.update({
    id: '/collection/$id',
    path: '/collection/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionIdDocumentsRoute =
  AuthenticatedCollectionIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCollectionIdRoute,
  } as any)
const AuthenticatedCollectionIdChatRoute =
  AuthenticatedCollectionIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedCollectionIdRoute,
  } as any)
const AuthenticatedAuthAdminAdminUsersIndexRoute =
  AuthenticatedAuthAdminAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedAuthAdminRoute,
  } as any)
const AuthenticatedAuthAdminAdminUsersIdRoute =
  AuthenticatedAuthAdminAdminUsersIdRouteImport.update({
    id: '/admin/users/$id',
    path: '/admin/users/$id',
    getParentRoute: () => AuthenticatedAuthAdminRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionNewRoute =
  AuthenticatedAuthAdminAdminCollectionNewRouteImport.update({
    id: '/admin/collection/new',
    path: '/admin/collection/new',
    getParentRoute: () => AuthenticatedAuthAdminRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionIdRoute =
  AuthenticatedAuthAdminAdminCollectionIdRouteImport.update({
    id: '/admin/collection/$id',
    path: '/admin/collection/$id',
    getParentRoute: () => AuthenticatedAuthAdminRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionIdUsersRoute =
  AuthenticatedAuthAdminAdminCollectionIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionIdRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionIdUpdateRoute =
  AuthenticatedAuthAdminAdminCollectionIdUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionIdRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionIdReindexRoute =
  AuthenticatedAuthAdminAdminCollectionIdReindexRouteImport.update({
    id: '/reindex',
    path: '/reindex',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionIdRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionIdInsertRoute =
  AuthenticatedAuthAdminAdminCollectionIdInsertRouteImport.update({
    id: '/insert',
    path: '/insert',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionIdRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionIdDocumentsRoute =
  AuthenticatedAuthAdminAdminCollectionIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionIdRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionIdDeleteRoute =
  AuthenticatedAuthAdminAdminCollectionIdDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/collection/$id': typeof AuthenticatedCollectionIdRouteWithChildren
  '/collection/$id/chat': typeof AuthenticatedCollectionIdChatRoute
  '/collection/$id/documents': typeof AuthenticatedCollectionIdDocumentsRoute
  '/admin/collection/$id': typeof AuthenticatedAuthAdminAdminCollectionIdRouteWithChildren
  '/admin/collection/new': typeof AuthenticatedAuthAdminAdminCollectionNewRoute
  '/admin/users/$id': typeof AuthenticatedAuthAdminAdminUsersIdRoute
  '/admin/users/': typeof AuthenticatedAuthAdminAdminUsersIndexRoute
  '/admin/collection/$id/delete': typeof AuthenticatedAuthAdminAdminCollectionIdDeleteRoute
  '/admin/collection/$id/documents': typeof AuthenticatedAuthAdminAdminCollectionIdDocumentsRoute
  '/admin/collection/$id/insert': typeof AuthenticatedAuthAdminAdminCollectionIdInsertRoute
  '/admin/collection/$id/reindex': typeof AuthenticatedAuthAdminAdminCollectionIdReindexRoute
  '/admin/collection/$id/update': typeof AuthenticatedAuthAdminAdminCollectionIdUpdateRoute
  '/admin/collection/$id/users': typeof AuthenticatedAuthAdminAdminCollectionIdUsersRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/collection/$id': typeof AuthenticatedCollectionIdRouteWithChildren
  '/collection/$id/chat': typeof AuthenticatedCollectionIdChatRoute
  '/collection/$id/documents': typeof AuthenticatedCollectionIdDocumentsRoute
  '/admin/collection/$id': typeof AuthenticatedAuthAdminAdminCollectionIdRouteWithChildren
  '/admin/collection/new': typeof AuthenticatedAuthAdminAdminCollectionNewRoute
  '/admin/users/$id': typeof AuthenticatedAuthAdminAdminUsersIdRoute
  '/admin/users': typeof AuthenticatedAuthAdminAdminUsersIndexRoute
  '/admin/collection/$id/delete': typeof AuthenticatedAuthAdminAdminCollectionIdDeleteRoute
  '/admin/collection/$id/documents': typeof AuthenticatedAuthAdminAdminCollectionIdDocumentsRoute
  '/admin/collection/$id/insert': typeof AuthenticatedAuthAdminAdminCollectionIdInsertRoute
  '/admin/collection/$id/reindex': typeof AuthenticatedAuthAdminAdminCollectionIdReindexRoute
  '/admin/collection/$id/update': typeof AuthenticatedAuthAdminAdminCollectionIdUpdateRoute
  '/admin/collection/$id/users': typeof AuthenticatedAuthAdminAdminCollectionIdUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_authAdmin': typeof AuthenticatedAuthAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/collection/$id': typeof AuthenticatedCollectionIdRouteWithChildren
  '/_authenticated/collection/$id/chat': typeof AuthenticatedCollectionIdChatRoute
  '/_authenticated/collection/$id/documents': typeof AuthenticatedCollectionIdDocumentsRoute
  '/_authenticated/_authAdmin/admin/collection/$id': typeof AuthenticatedAuthAdminAdminCollectionIdRouteWithChildren
  '/_authenticated/_authAdmin/admin/collection/new': typeof AuthenticatedAuthAdminAdminCollectionNewRoute
  '/_authenticated/_authAdmin/admin/users/$id': typeof AuthenticatedAuthAdminAdminUsersIdRoute
  '/_authenticated/_authAdmin/admin/users/': typeof AuthenticatedAuthAdminAdminUsersIndexRoute
  '/_authenticated/_authAdmin/admin/collection/$id/delete': typeof AuthenticatedAuthAdminAdminCollectionIdDeleteRoute
  '/_authenticated/_authAdmin/admin/collection/$id/documents': typeof AuthenticatedAuthAdminAdminCollectionIdDocumentsRoute
  '/_authenticated/_authAdmin/admin/collection/$id/insert': typeof AuthenticatedAuthAdminAdminCollectionIdInsertRoute
  '/_authenticated/_authAdmin/admin/collection/$id/reindex': typeof AuthenticatedAuthAdminAdminCollectionIdReindexRoute
  '/_authenticated/_authAdmin/admin/collection/$id/update': typeof AuthenticatedAuthAdminAdminCollectionIdUpdateRoute
  '/_authenticated/_authAdmin/admin/collection/$id/users': typeof AuthenticatedAuthAdminAdminCollectionIdUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/register'
    | '/profile'
    | '/collection/$id'
    | '/collection/$id/chat'
    | '/collection/$id/documents'
    | '/admin/collection/$id'
    | '/admin/collection/new'
    | '/admin/users/$id'
    | '/admin/users/'
    | '/admin/collection/$id/delete'
    | '/admin/collection/$id/documents'
    | '/admin/collection/$id/insert'
    | '/admin/collection/$id/reindex'
    | '/admin/collection/$id/update'
    | '/admin/collection/$id/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/register'
    | '/'
    | '/profile'
    | '/collection/$id'
    | '/collection/$id/chat'
    | '/collection/$id/documents'
    | '/admin/collection/$id'
    | '/admin/collection/new'
    | '/admin/users/$id'
    | '/admin/users'
    | '/admin/collection/$id/delete'
    | '/admin/collection/$id/documents'
    | '/admin/collection/$id/insert'
    | '/admin/collection/$id/reindex'
    | '/admin/collection/$id/update'
    | '/admin/collection/$id/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/change-password'
    | '/login'
    | '/register'
    | '/_authenticated/_authAdmin'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/collection/$id'
    | '/_authenticated/collection/$id/chat'
    | '/_authenticated/collection/$id/documents'
    | '/_authenticated/_authAdmin/admin/collection/$id'
    | '/_authenticated/_authAdmin/admin/collection/new'
    | '/_authenticated/_authAdmin/admin/users/$id'
    | '/_authenticated/_authAdmin/admin/users/'
    | '/_authenticated/_authAdmin/admin/collection/$id/delete'
    | '/_authenticated/_authAdmin/admin/collection/$id/documents'
    | '/_authenticated/_authAdmin/admin/collection/$id/insert'
    | '/_authenticated/_authAdmin/admin/collection/$id/reindex'
    | '/_authenticated/_authAdmin/admin/collection/$id/update'
    | '/_authenticated/_authAdmin/admin/collection/$id/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_authAdmin': {
      id: '/_authenticated/_authAdmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAuthAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection/$id': {
      id: '/_authenticated/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof AuthenticatedCollectionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection/$id/documents': {
      id: '/_authenticated/collection/$id/documents'
      path: '/documents'
      fullPath: '/collection/$id/documents'
      preLoaderRoute: typeof AuthenticatedCollectionIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedCollectionIdRoute
    }
    '/_authenticated/collection/$id/chat': {
      id: '/_authenticated/collection/$id/chat'
      path: '/chat'
      fullPath: '/collection/$id/chat'
      preLoaderRoute: typeof AuthenticatedCollectionIdChatRouteImport
      parentRoute: typeof AuthenticatedCollectionIdRoute
    }
    '/_authenticated/_authAdmin/admin/users/': {
      id: '/_authenticated/_authAdmin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAuthAdminRoute
    }
    '/_authenticated/_authAdmin/admin/users/$id': {
      id: '/_authenticated/_authAdmin/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAuthAdminRoute
    }
    '/_authenticated/_authAdmin/admin/collection/new': {
      id: '/_authenticated/_authAdmin/admin/collection/new'
      path: '/admin/collection/new'
      fullPath: '/admin/collection/new'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionNewRouteImport
      parentRoute: typeof AuthenticatedAuthAdminRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$id': {
      id: '/_authenticated/_authAdmin/admin/collection/$id'
      path: '/admin/collection/$id'
      fullPath: '/admin/collection/$id'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionIdRouteImport
      parentRoute: typeof AuthenticatedAuthAdminRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$id/users': {
      id: '/_authenticated/_authAdmin/admin/collection/$id/users'
      path: '/users'
      fullPath: '/admin/collection/$id/users'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionIdUsersRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionIdRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$id/update': {
      id: '/_authenticated/_authAdmin/admin/collection/$id/update'
      path: '/update'
      fullPath: '/admin/collection/$id/update'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionIdUpdateRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionIdRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$id/reindex': {
      id: '/_authenticated/_authAdmin/admin/collection/$id/reindex'
      path: '/reindex'
      fullPath: '/admin/collection/$id/reindex'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionIdReindexRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionIdRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$id/insert': {
      id: '/_authenticated/_authAdmin/admin/collection/$id/insert'
      path: '/insert'
      fullPath: '/admin/collection/$id/insert'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionIdInsertRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionIdRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$id/documents': {
      id: '/_authenticated/_authAdmin/admin/collection/$id/documents'
      path: '/documents'
      fullPath: '/admin/collection/$id/documents'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionIdRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$id/delete': {
      id: '/_authenticated/_authAdmin/admin/collection/$id/delete'
      path: '/delete'
      fullPath: '/admin/collection/$id/delete'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionIdDeleteRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionIdRoute
    }
  }
}

interface AuthenticatedAuthAdminAdminCollectionIdRouteChildren {
  AuthenticatedAuthAdminAdminCollectionIdDeleteRoute: typeof AuthenticatedAuthAdminAdminCollectionIdDeleteRoute
  AuthenticatedAuthAdminAdminCollectionIdDocumentsRoute: typeof AuthenticatedAuthAdminAdminCollectionIdDocumentsRoute
  AuthenticatedAuthAdminAdminCollectionIdInsertRoute: typeof AuthenticatedAuthAdminAdminCollectionIdInsertRoute
  AuthenticatedAuthAdminAdminCollectionIdReindexRoute: typeof AuthenticatedAuthAdminAdminCollectionIdReindexRoute
  AuthenticatedAuthAdminAdminCollectionIdUpdateRoute: typeof AuthenticatedAuthAdminAdminCollectionIdUpdateRoute
  AuthenticatedAuthAdminAdminCollectionIdUsersRoute: typeof AuthenticatedAuthAdminAdminCollectionIdUsersRoute
}

const AuthenticatedAuthAdminAdminCollectionIdRouteChildren: AuthenticatedAuthAdminAdminCollectionIdRouteChildren =
  {
    AuthenticatedAuthAdminAdminCollectionIdDeleteRoute:
      AuthenticatedAuthAdminAdminCollectionIdDeleteRoute,
    AuthenticatedAuthAdminAdminCollectionIdDocumentsRoute:
      AuthenticatedAuthAdminAdminCollectionIdDocumentsRoute,
    AuthenticatedAuthAdminAdminCollectionIdInsertRoute:
      AuthenticatedAuthAdminAdminCollectionIdInsertRoute,
    AuthenticatedAuthAdminAdminCollectionIdReindexRoute:
      AuthenticatedAuthAdminAdminCollectionIdReindexRoute,
    AuthenticatedAuthAdminAdminCollectionIdUpdateRoute:
      AuthenticatedAuthAdminAdminCollectionIdUpdateRoute,
    AuthenticatedAuthAdminAdminCollectionIdUsersRoute:
      AuthenticatedAuthAdminAdminCollectionIdUsersRoute,
  }

const AuthenticatedAuthAdminAdminCollectionIdRouteWithChildren =
  AuthenticatedAuthAdminAdminCollectionIdRoute._addFileChildren(
    AuthenticatedAuthAdminAdminCollectionIdRouteChildren,
  )

interface AuthenticatedAuthAdminRouteChildren {
  AuthenticatedAuthAdminAdminCollectionIdRoute: typeof AuthenticatedAuthAdminAdminCollectionIdRouteWithChildren
  AuthenticatedAuthAdminAdminCollectionNewRoute: typeof AuthenticatedAuthAdminAdminCollectionNewRoute
  AuthenticatedAuthAdminAdminUsersIdRoute: typeof AuthenticatedAuthAdminAdminUsersIdRoute
  AuthenticatedAuthAdminAdminUsersIndexRoute: typeof AuthenticatedAuthAdminAdminUsersIndexRoute
}

const AuthenticatedAuthAdminRouteChildren: AuthenticatedAuthAdminRouteChildren =
  {
    AuthenticatedAuthAdminAdminCollectionIdRoute:
      AuthenticatedAuthAdminAdminCollectionIdRouteWithChildren,
    AuthenticatedAuthAdminAdminCollectionNewRoute:
      AuthenticatedAuthAdminAdminCollectionNewRoute,
    AuthenticatedAuthAdminAdminUsersIdRoute:
      AuthenticatedAuthAdminAdminUsersIdRoute,
    AuthenticatedAuthAdminAdminUsersIndexRoute:
      AuthenticatedAuthAdminAdminUsersIndexRoute,
  }

const AuthenticatedAuthAdminRouteWithChildren =
  AuthenticatedAuthAdminRoute._addFileChildren(
    AuthenticatedAuthAdminRouteChildren,
  )

interface AuthenticatedCollectionIdRouteChildren {
  AuthenticatedCollectionIdChatRoute: typeof AuthenticatedCollectionIdChatRoute
  AuthenticatedCollectionIdDocumentsRoute: typeof AuthenticatedCollectionIdDocumentsRoute
}

const AuthenticatedCollectionIdRouteChildren: AuthenticatedCollectionIdRouteChildren =
  {
    AuthenticatedCollectionIdChatRoute: AuthenticatedCollectionIdChatRoute,
    AuthenticatedCollectionIdDocumentsRoute:
      AuthenticatedCollectionIdDocumentsRoute,
  }

const AuthenticatedCollectionIdRouteWithChildren =
  AuthenticatedCollectionIdRoute._addFileChildren(
    AuthenticatedCollectionIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuthAdminRoute: typeof AuthenticatedAuthAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCollectionIdRoute: typeof AuthenticatedCollectionIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthAdminRoute: AuthenticatedAuthAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCollectionIdRoute: AuthenticatedCollectionIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
