/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfoRouteImport } from './routes/info'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAuthAdminRouteImport } from './routes/_authenticated/_authAdmin'
import { Route as AuthenticatedCollectionSlugRouteImport } from './routes/_authenticated/collection/$slug'
import { Route as AuthenticatedCollectionSlugDocumentsRouteImport } from './routes/_authenticated/collection/$slug/documents'
import { Route as AuthenticatedCollectionSlugChatRouteImport } from './routes/_authenticated/collection/$slug/chat'
import { Route as AuthenticatedAuthAdminAdminUsersIndexRouteImport } from './routes/_authenticated/_authAdmin/admin/users/index'
import { Route as AuthenticatedAuthAdminAdminUsersSlugRouteImport } from './routes/_authenticated/_authAdmin/admin/users/$slug'
import { Route as AuthenticatedAuthAdminAdminCollectionNewRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/new'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugIndexRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug/index'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugUsersRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug/users'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugUpdateRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug/update'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugReindexRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug/reindex'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugManagersRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug/managers'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugInsertRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug/insert'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugDocumentsRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug/documents'
import { Route as AuthenticatedAuthAdminAdminCollectionSlugDeleteRouteImport } from './routes/_authenticated/_authAdmin/admin/collection/$slug/delete'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthAdminRoute = AuthenticatedAuthAdminRouteImport.update({
  id: '/_authAdmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionSlugRoute =
  AuthenticatedCollectionSlugRouteImport.update({
    id: '/collection/$slug',
    path: '/collection/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionSlugDocumentsRoute =
  AuthenticatedCollectionSlugDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCollectionSlugRoute,
  } as any)
const AuthenticatedCollectionSlugChatRoute =
  AuthenticatedCollectionSlugChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedCollectionSlugRoute,
  } as any)
const AuthenticatedAuthAdminAdminUsersIndexRoute =
  AuthenticatedAuthAdminAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedAuthAdminRoute,
  } as any)
const AuthenticatedAuthAdminAdminUsersSlugRoute =
  AuthenticatedAuthAdminAdminUsersSlugRouteImport.update({
    id: '/admin/users/$slug',
    path: '/admin/users/$slug',
    getParentRoute: () => AuthenticatedAuthAdminRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionNewRoute =
  AuthenticatedAuthAdminAdminCollectionNewRouteImport.update({
    id: '/admin/collection/new',
    path: '/admin/collection/new',
    getParentRoute: () => AuthenticatedAuthAdminRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugRoute =
  AuthenticatedAuthAdminAdminCollectionSlugRouteImport.update({
    id: '/admin/collection/$slug',
    path: '/admin/collection/$slug',
    getParentRoute: () => AuthenticatedAuthAdminRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugIndexRoute =
  AuthenticatedAuthAdminAdminCollectionSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionSlugRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugUsersRoute =
  AuthenticatedAuthAdminAdminCollectionSlugUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionSlugRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugUpdateRoute =
  AuthenticatedAuthAdminAdminCollectionSlugUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionSlugRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugReindexRoute =
  AuthenticatedAuthAdminAdminCollectionSlugReindexRouteImport.update({
    id: '/reindex',
    path: '/reindex',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionSlugRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugManagersRoute =
  AuthenticatedAuthAdminAdminCollectionSlugManagersRouteImport.update({
    id: '/managers',
    path: '/managers',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionSlugRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugInsertRoute =
  AuthenticatedAuthAdminAdminCollectionSlugInsertRouteImport.update({
    id: '/insert',
    path: '/insert',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionSlugRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugDocumentsRoute =
  AuthenticatedAuthAdminAdminCollectionSlugDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionSlugRoute,
  } as any)
const AuthenticatedAuthAdminAdminCollectionSlugDeleteRoute =
  AuthenticatedAuthAdminAdminCollectionSlugDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthenticatedAuthAdminAdminCollectionSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/collection/$slug': typeof AuthenticatedCollectionSlugRouteWithChildren
  '/collection/$slug/chat': typeof AuthenticatedCollectionSlugChatRoute
  '/collection/$slug/documents': typeof AuthenticatedCollectionSlugDocumentsRoute
  '/admin/collection/$slug': typeof AuthenticatedAuthAdminAdminCollectionSlugRouteWithChildren
  '/admin/collection/new': typeof AuthenticatedAuthAdminAdminCollectionNewRoute
  '/admin/users/$slug': typeof AuthenticatedAuthAdminAdminUsersSlugRoute
  '/admin/users/': typeof AuthenticatedAuthAdminAdminUsersIndexRoute
  '/admin/collection/$slug/delete': typeof AuthenticatedAuthAdminAdminCollectionSlugDeleteRoute
  '/admin/collection/$slug/documents': typeof AuthenticatedAuthAdminAdminCollectionSlugDocumentsRoute
  '/admin/collection/$slug/insert': typeof AuthenticatedAuthAdminAdminCollectionSlugInsertRoute
  '/admin/collection/$slug/managers': typeof AuthenticatedAuthAdminAdminCollectionSlugManagersRoute
  '/admin/collection/$slug/reindex': typeof AuthenticatedAuthAdminAdminCollectionSlugReindexRoute
  '/admin/collection/$slug/update': typeof AuthenticatedAuthAdminAdminCollectionSlugUpdateRoute
  '/admin/collection/$slug/users': typeof AuthenticatedAuthAdminAdminCollectionSlugUsersRoute
  '/admin/collection/$slug/': typeof AuthenticatedAuthAdminAdminCollectionSlugIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/collection/$slug': typeof AuthenticatedCollectionSlugRouteWithChildren
  '/collection/$slug/chat': typeof AuthenticatedCollectionSlugChatRoute
  '/collection/$slug/documents': typeof AuthenticatedCollectionSlugDocumentsRoute
  '/admin/collection/new': typeof AuthenticatedAuthAdminAdminCollectionNewRoute
  '/admin/users/$slug': typeof AuthenticatedAuthAdminAdminUsersSlugRoute
  '/admin/users': typeof AuthenticatedAuthAdminAdminUsersIndexRoute
  '/admin/collection/$slug/delete': typeof AuthenticatedAuthAdminAdminCollectionSlugDeleteRoute
  '/admin/collection/$slug/documents': typeof AuthenticatedAuthAdminAdminCollectionSlugDocumentsRoute
  '/admin/collection/$slug/insert': typeof AuthenticatedAuthAdminAdminCollectionSlugInsertRoute
  '/admin/collection/$slug/managers': typeof AuthenticatedAuthAdminAdminCollectionSlugManagersRoute
  '/admin/collection/$slug/reindex': typeof AuthenticatedAuthAdminAdminCollectionSlugReindexRoute
  '/admin/collection/$slug/update': typeof AuthenticatedAuthAdminAdminCollectionSlugUpdateRoute
  '/admin/collection/$slug/users': typeof AuthenticatedAuthAdminAdminCollectionSlugUsersRoute
  '/admin/collection/$slug': typeof AuthenticatedAuthAdminAdminCollectionSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/info': typeof InfoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_authAdmin': typeof AuthenticatedAuthAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/collection/$slug': typeof AuthenticatedCollectionSlugRouteWithChildren
  '/_authenticated/collection/$slug/chat': typeof AuthenticatedCollectionSlugChatRoute
  '/_authenticated/collection/$slug/documents': typeof AuthenticatedCollectionSlugDocumentsRoute
  '/_authenticated/_authAdmin/admin/collection/$slug': typeof AuthenticatedAuthAdminAdminCollectionSlugRouteWithChildren
  '/_authenticated/_authAdmin/admin/collection/new': typeof AuthenticatedAuthAdminAdminCollectionNewRoute
  '/_authenticated/_authAdmin/admin/users/$slug': typeof AuthenticatedAuthAdminAdminUsersSlugRoute
  '/_authenticated/_authAdmin/admin/users/': typeof AuthenticatedAuthAdminAdminUsersIndexRoute
  '/_authenticated/_authAdmin/admin/collection/$slug/delete': typeof AuthenticatedAuthAdminAdminCollectionSlugDeleteRoute
  '/_authenticated/_authAdmin/admin/collection/$slug/documents': typeof AuthenticatedAuthAdminAdminCollectionSlugDocumentsRoute
  '/_authenticated/_authAdmin/admin/collection/$slug/insert': typeof AuthenticatedAuthAdminAdminCollectionSlugInsertRoute
  '/_authenticated/_authAdmin/admin/collection/$slug/managers': typeof AuthenticatedAuthAdminAdminCollectionSlugManagersRoute
  '/_authenticated/_authAdmin/admin/collection/$slug/reindex': typeof AuthenticatedAuthAdminAdminCollectionSlugReindexRoute
  '/_authenticated/_authAdmin/admin/collection/$slug/update': typeof AuthenticatedAuthAdminAdminCollectionSlugUpdateRoute
  '/_authenticated/_authAdmin/admin/collection/$slug/users': typeof AuthenticatedAuthAdminAdminCollectionSlugUsersRoute
  '/_authenticated/_authAdmin/admin/collection/$slug/': typeof AuthenticatedAuthAdminAdminCollectionSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/info'
    | '/login'
    | '/register'
    | '/profile'
    | '/collection/$slug'
    | '/collection/$slug/chat'
    | '/collection/$slug/documents'
    | '/admin/collection/$slug'
    | '/admin/collection/new'
    | '/admin/users/$slug'
    | '/admin/users/'
    | '/admin/collection/$slug/delete'
    | '/admin/collection/$slug/documents'
    | '/admin/collection/$slug/insert'
    | '/admin/collection/$slug/managers'
    | '/admin/collection/$slug/reindex'
    | '/admin/collection/$slug/update'
    | '/admin/collection/$slug/users'
    | '/admin/collection/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/info'
    | '/login'
    | '/register'
    | '/'
    | '/profile'
    | '/collection/$slug'
    | '/collection/$slug/chat'
    | '/collection/$slug/documents'
    | '/admin/collection/new'
    | '/admin/users/$slug'
    | '/admin/users'
    | '/admin/collection/$slug/delete'
    | '/admin/collection/$slug/documents'
    | '/admin/collection/$slug/insert'
    | '/admin/collection/$slug/managers'
    | '/admin/collection/$slug/reindex'
    | '/admin/collection/$slug/update'
    | '/admin/collection/$slug/users'
    | '/admin/collection/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/change-password'
    | '/info'
    | '/login'
    | '/register'
    | '/_authenticated/_authAdmin'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/collection/$slug'
    | '/_authenticated/collection/$slug/chat'
    | '/_authenticated/collection/$slug/documents'
    | '/_authenticated/_authAdmin/admin/collection/$slug'
    | '/_authenticated/_authAdmin/admin/collection/new'
    | '/_authenticated/_authAdmin/admin/users/$slug'
    | '/_authenticated/_authAdmin/admin/users/'
    | '/_authenticated/_authAdmin/admin/collection/$slug/delete'
    | '/_authenticated/_authAdmin/admin/collection/$slug/documents'
    | '/_authenticated/_authAdmin/admin/collection/$slug/insert'
    | '/_authenticated/_authAdmin/admin/collection/$slug/managers'
    | '/_authenticated/_authAdmin/admin/collection/$slug/reindex'
    | '/_authenticated/_authAdmin/admin/collection/$slug/update'
    | '/_authenticated/_authAdmin/admin/collection/$slug/users'
    | '/_authenticated/_authAdmin/admin/collection/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  InfoRoute: typeof InfoRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_authAdmin': {
      id: '/_authenticated/_authAdmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAuthAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection/$slug': {
      id: '/_authenticated/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof AuthenticatedCollectionSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection/$slug/documents': {
      id: '/_authenticated/collection/$slug/documents'
      path: '/documents'
      fullPath: '/collection/$slug/documents'
      preLoaderRoute: typeof AuthenticatedCollectionSlugDocumentsRouteImport
      parentRoute: typeof AuthenticatedCollectionSlugRoute
    }
    '/_authenticated/collection/$slug/chat': {
      id: '/_authenticated/collection/$slug/chat'
      path: '/chat'
      fullPath: '/collection/$slug/chat'
      preLoaderRoute: typeof AuthenticatedCollectionSlugChatRouteImport
      parentRoute: typeof AuthenticatedCollectionSlugRoute
    }
    '/_authenticated/_authAdmin/admin/users/': {
      id: '/_authenticated/_authAdmin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAuthAdminRoute
    }
    '/_authenticated/_authAdmin/admin/users/$slug': {
      id: '/_authenticated/_authAdmin/admin/users/$slug'
      path: '/admin/users/$slug'
      fullPath: '/admin/users/$slug'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminUsersSlugRouteImport
      parentRoute: typeof AuthenticatedAuthAdminRoute
    }
    '/_authenticated/_authAdmin/admin/collection/new': {
      id: '/_authenticated/_authAdmin/admin/collection/new'
      path: '/admin/collection/new'
      fullPath: '/admin/collection/new'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionNewRouteImport
      parentRoute: typeof AuthenticatedAuthAdminRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug'
      path: '/admin/collection/$slug'
      fullPath: '/admin/collection/$slug'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRouteImport
      parentRoute: typeof AuthenticatedAuthAdminRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug/': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug/'
      path: '/'
      fullPath: '/admin/collection/$slug/'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugIndexRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug/users': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug/users'
      path: '/users'
      fullPath: '/admin/collection/$slug/users'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugUsersRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug/update': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug/update'
      path: '/update'
      fullPath: '/admin/collection/$slug/update'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugUpdateRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug/reindex': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug/reindex'
      path: '/reindex'
      fullPath: '/admin/collection/$slug/reindex'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugReindexRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug/managers': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug/managers'
      path: '/managers'
      fullPath: '/admin/collection/$slug/managers'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugManagersRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug/insert': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug/insert'
      path: '/insert'
      fullPath: '/admin/collection/$slug/insert'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugInsertRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug/documents': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug/documents'
      path: '/documents'
      fullPath: '/admin/collection/$slug/documents'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugDocumentsRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRoute
    }
    '/_authenticated/_authAdmin/admin/collection/$slug/delete': {
      id: '/_authenticated/_authAdmin/admin/collection/$slug/delete'
      path: '/delete'
      fullPath: '/admin/collection/$slug/delete'
      preLoaderRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugDeleteRouteImport
      parentRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRoute
    }
  }
}

interface AuthenticatedAuthAdminAdminCollectionSlugRouteChildren {
  AuthenticatedAuthAdminAdminCollectionSlugDeleteRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugDeleteRoute
  AuthenticatedAuthAdminAdminCollectionSlugDocumentsRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugDocumentsRoute
  AuthenticatedAuthAdminAdminCollectionSlugInsertRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugInsertRoute
  AuthenticatedAuthAdminAdminCollectionSlugManagersRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugManagersRoute
  AuthenticatedAuthAdminAdminCollectionSlugReindexRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugReindexRoute
  AuthenticatedAuthAdminAdminCollectionSlugUpdateRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugUpdateRoute
  AuthenticatedAuthAdminAdminCollectionSlugUsersRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugUsersRoute
  AuthenticatedAuthAdminAdminCollectionSlugIndexRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugIndexRoute
}

const AuthenticatedAuthAdminAdminCollectionSlugRouteChildren: AuthenticatedAuthAdminAdminCollectionSlugRouteChildren =
  {
    AuthenticatedAuthAdminAdminCollectionSlugDeleteRoute:
      AuthenticatedAuthAdminAdminCollectionSlugDeleteRoute,
    AuthenticatedAuthAdminAdminCollectionSlugDocumentsRoute:
      AuthenticatedAuthAdminAdminCollectionSlugDocumentsRoute,
    AuthenticatedAuthAdminAdminCollectionSlugInsertRoute:
      AuthenticatedAuthAdminAdminCollectionSlugInsertRoute,
    AuthenticatedAuthAdminAdminCollectionSlugManagersRoute:
      AuthenticatedAuthAdminAdminCollectionSlugManagersRoute,
    AuthenticatedAuthAdminAdminCollectionSlugReindexRoute:
      AuthenticatedAuthAdminAdminCollectionSlugReindexRoute,
    AuthenticatedAuthAdminAdminCollectionSlugUpdateRoute:
      AuthenticatedAuthAdminAdminCollectionSlugUpdateRoute,
    AuthenticatedAuthAdminAdminCollectionSlugUsersRoute:
      AuthenticatedAuthAdminAdminCollectionSlugUsersRoute,
    AuthenticatedAuthAdminAdminCollectionSlugIndexRoute:
      AuthenticatedAuthAdminAdminCollectionSlugIndexRoute,
  }

const AuthenticatedAuthAdminAdminCollectionSlugRouteWithChildren =
  AuthenticatedAuthAdminAdminCollectionSlugRoute._addFileChildren(
    AuthenticatedAuthAdminAdminCollectionSlugRouteChildren,
  )

interface AuthenticatedAuthAdminRouteChildren {
  AuthenticatedAuthAdminAdminCollectionSlugRoute: typeof AuthenticatedAuthAdminAdminCollectionSlugRouteWithChildren
  AuthenticatedAuthAdminAdminCollectionNewRoute: typeof AuthenticatedAuthAdminAdminCollectionNewRoute
  AuthenticatedAuthAdminAdminUsersSlugRoute: typeof AuthenticatedAuthAdminAdminUsersSlugRoute
  AuthenticatedAuthAdminAdminUsersIndexRoute: typeof AuthenticatedAuthAdminAdminUsersIndexRoute
}

const AuthenticatedAuthAdminRouteChildren: AuthenticatedAuthAdminRouteChildren =
  {
    AuthenticatedAuthAdminAdminCollectionSlugRoute:
      AuthenticatedAuthAdminAdminCollectionSlugRouteWithChildren,
    AuthenticatedAuthAdminAdminCollectionNewRoute:
      AuthenticatedAuthAdminAdminCollectionNewRoute,
    AuthenticatedAuthAdminAdminUsersSlugRoute:
      AuthenticatedAuthAdminAdminUsersSlugRoute,
    AuthenticatedAuthAdminAdminUsersIndexRoute:
      AuthenticatedAuthAdminAdminUsersIndexRoute,
  }

const AuthenticatedAuthAdminRouteWithChildren =
  AuthenticatedAuthAdminRoute._addFileChildren(
    AuthenticatedAuthAdminRouteChildren,
  )

interface AuthenticatedCollectionSlugRouteChildren {
  AuthenticatedCollectionSlugChatRoute: typeof AuthenticatedCollectionSlugChatRoute
  AuthenticatedCollectionSlugDocumentsRoute: typeof AuthenticatedCollectionSlugDocumentsRoute
}

const AuthenticatedCollectionSlugRouteChildren: AuthenticatedCollectionSlugRouteChildren =
  {
    AuthenticatedCollectionSlugChatRoute: AuthenticatedCollectionSlugChatRoute,
    AuthenticatedCollectionSlugDocumentsRoute:
      AuthenticatedCollectionSlugDocumentsRoute,
  }

const AuthenticatedCollectionSlugRouteWithChildren =
  AuthenticatedCollectionSlugRoute._addFileChildren(
    AuthenticatedCollectionSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuthAdminRoute: typeof AuthenticatedAuthAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCollectionSlugRoute: typeof AuthenticatedCollectionSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthAdminRoute: AuthenticatedAuthAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCollectionSlugRoute:
    AuthenticatedCollectionSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  InfoRoute: InfoRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
