"""add_uuid_to_collections

Revision ID: 451d22a2514c
Revises: 6bd270638a43
Create Date: 2026-04-12 17:23:42.238818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451d22a2514c'
down_revision: Union[str, Sequence[str], None] = '6bd270638a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_collections_uuid'), 'collections', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_uuid'), table_name='collections')
    op.drop_column('collections', 'uuid')
    # ### end Alembic commands ###
