"""add_filename_to_job_ingestion

Revision ID: 6bd270638a43
Revises: 2f8a9b0c1d34
Create Date: 2026-04-09 21:38:15.787340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bd270638a43'
down_revision: Union[str, Sequence[str], None] = '2f8a9b0c1d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'documents', 'collections', ['collection_id'], ['id'])
    # Ajouter filename nullable d'abord (car des lignes existantes)
    op.add_column('job_ingestion', sa.Column('filename', sa.String(length=255), nullable=True))
    # Remplir les valeurs null avec une chaîne vide
    op.execute("UPDATE job_ingestion SET filename = '' WHERE filename IS NULL")
    # Rendre la colonne NOT NULL
    op.alter_column('job_ingestion', 'filename',
               existing_type=sa.String(length=255),
               nullable=False)
    op.alter_column('job_ingestion', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('job_ingestion', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_ingestion', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_ingestion', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('job_ingestion', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_ingestion', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # Supprimer filename (les données seront perdues)
    op.drop_column('job_ingestion', 'filename')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    # ### end Alembic commands ###
